### ISSUE TITLE
Zaproxy Error: Data File size limit is reached

### ISSUE THREAD

**Issue by lfatty** [continuumsecurity/bdd-security#40]
This is the error that keep showing during scan:

[ZAP-ActiveScanner-1] FATAL hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - data file reached maximum size /var/lib/jenkins/.ZAP/session/untitled1.data
     [java] 106425634 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascan.ActiveScan  - java.sql.SQLException: Data File size limit is reached
     [java] org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Data File size limit is reached
     [java] 	at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)
     [java] 	at org.parosproxy.paros.model.HistoryReference.<init>(Unknown Source)
     [java] 	at org.zaproxy.zap.extension.ascan.ActiveScan.notifyNewMessage(Unknown Source)
     [java] 	at org.parosproxy.paros.core.scanner.HostProcess.notifyNewMessage(Unknown Source)
     [java] 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
     [java] 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
     [java] 	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
     [java] 	at org.zaproxy.zap.extension.ascanrules.TestCrossSiteScriptV2.performAttack(TestCrossSiteScriptV2.java:105)
     [java] 	at org.zaproxy.zap.extension.ascanrules.TestCrossSiteScriptV2.scan(TestCrossSiteScriptV2.java:220)
     [java] 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
     [java] 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(Unknown Source)
     [java] 	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
     [java] 	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(Unknown Source)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.sql.SQLException: Data File size limit is reached
     [java] 	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
     [java] 	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
     [java] 	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
     [java] 	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
     [java] 	at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)

**Comment by continuumsecurity** [comment]
This is a ZAP error, please raise it on ZAP project mailing list or issue tracker.
