### ISSUE TITLE
Is there dependies should i install to with bdd-security 

### ISSUE THREAD

**Issue by wassilaahamila** [continuumsecurity/bdd-security#44]
i installed bdd-security and try to configure it to work with my php web application, but there was a lot of errors when BUILD , such as selenium (import org.openqa.selenium.WebElement;  and so many ones ..) jbehave (import org.jbehave.core.annotations.*; ...) , htmlunit with selenium ...
what shall i do ?

**Comment by continuumsecurity** [comment]
Just after installation you should run: 
     `ant resolve`
To download the dependencies.

**Comment by wassilaahamila** [comment]
thnak's (y)

**Comment by wassilaahamila** [comment]
Hello, i changed the baseUrl to access to my application http://localhost://Forum/ and then  tried to run basic ZAP scanning: with the command below 
./runstory.sh app_scan
but an error is shown in the jBehave report : 

Automated Application Security Scanning
app_scan.story
Meta:
@story app_scan
Narrative:
In order to protect user data
As a n application owner
I want to ensure that the application does not suffer from common security vulnerabilities Meta: @story app_scan
GivenStories:
navigate_app.story
navigate_app.story
Scenario: Navigate and spider the application and find vulnerabilities through passive scanning
Meta:
@pre navigate
Given a new browser or client instance
And a new scanning session
And the passive scanner is enabled
And the page flow described in the method: navigate is run through the proxy (FAILED)
java.lang.reflect.InvocationTargetException
And the URL regular expressions listed in the file:
tables/exclude_urls.table
are excluded from the spider (NOT PERFORMED)
And the spider is configured for a maximum depth of 10 (NOT PERFORMED)
And the spider is configured for 1000 maximum children (NOT PERFORMED)
And the spider is configured for 10 concurrent threads (NOT PERFORMED)
And the following URLs are spidered:
url
baseUrl
(NOT PERFORMED)
And the spider status reaches 100% complete (NOT PERFORMED)
And the following false positives are removed:
tables/zap.false_positives.table
(NOT PERFORMED)
And the XML report is written to the file passive.xml (NOT PERFORMED)
Then no Medium or higher risk vulnerabilities should be present (NOT PERFORMED)

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.continuumsecurity.steps.AppScanningSteps.navigateApp(AppScanningSteps.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:569)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:533)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:513)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:477)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:308)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.runGivenStories(StoryRunner.java:393)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:272)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:235)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:207)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: no such element
  (Session info: chrome=49.0.2623.108)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.19.0-58-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 88 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'wassila-VPCEH3U1E', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-58-generic', java.version: '1.7.0_95'
Session ID: 2fe788151ecd64cee627f6c7abc1625d
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.2SPKeI}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.108, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByLinkText(RemoteWebDriver.java:401)
	at org.openqa.selenium.By$ByLinkText.findElement(By.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at net.continuumsecurity.examples.ropeytasks.forum.viewProfile(forum.java:86)
	at net.continuumsecurity.examples.ropeytasks.forum.viewProfileForWassila(forum.java:94)
	at net.continuumsecurity.examples.ropeytasks.forum.navigate(forum.java:138)
	... 25 more
