### ISSUE TITLE
connection exception

### ISSUE THREAD

**Issue by ionicappworld** [continuumsecurity/bdd-security#48]
Hi can anybody help me with the below error.
when i run through gradlew i am facing the below errors. 
1.
net.continuumsecurity.proxy.ProxyException
     Caused by: org.zaproxy.clientapi.core.ClientApiException
         Caused by: java.net.ConnectException
2.
        at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
        at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
        at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
        at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at org.parosproxy.paros.db.paros.ParosDatabaseServer.start(Unknown Sourc
e)
        at org.parosproxy.paros.db.paros.ParosDatabaseServer.<init>(Unknown Sour
ce)
        at org.parosproxy.paros.db.paros.ParosDatabase.open(Unknown Source)
        at org.parosproxy.paros.model.Model.createAndOpenUntitledDb(Unknown Sour
ce)
        at org.parosproxy.paros.model.Model.init(Unknown Source)
        at org.zaproxy.zap.ZapBootstrap.initModel(Unknown Source)
        at org.zaproxy.zap.DaemonBootstrap.start(Unknown Source)
        at org.zaproxy.zap.ZAP.main(Unknown Source)
Caused by: org.hsqldb.HsqlException: Database lock acquisition failure: lockFile
: org.hsqldb.persist.LockFile@a803b7c5[file =C:\Users\xxxx\Downloads\bdd-secu
rity-master\bdd-security-master\zap\tmp\session\untitled1.lck, exists=true, lock
ed=false, valid=false, ] method: checkHeartbeat read: 2016-06-14 10:18:56 heartb
eat - read: -875 ms.
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.errorn Source)
        at org.hsqldb.persist.LockFile.newLockFileLock(Unknown Source)
        at org.hsqldb.persist.Logger.acquireLock(Unknown Source)
        at org.hsqldb.persist.Logger.openPersistence(Unknown Source)
        at org.hsqldb.Database.reopen(Unknown Source)
        at org.hsqldb.Database.open(Unknown Source)
        at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
        at org.hsqldb.DatabaseManager.newSession(Unknown Source)

_The below is the cofig.xml is there anything wrong that i am doing over here, please confirm_

<?xml version="1.0" encoding="ISO-8859-1" ?>
<web-app>

    

    

    
    <baseUrl>myapplication URL/</baseUrl>

    
    <class>net.continuumsecurity.examples.ropeytasks.RopeyTasksApplication</class>

    <sslyze>
        <path>/opt/sslyze/sslyze_cli.py</path>
        <option>--regular</option>
    </sslyze>

    
    <sessionIds>
        <name>JSESSIONID</name>
    </sessionIds>

    
    <defaultUsername>username</defaultUsername>
    <defaultPassword>password</defaultPassword>

    <scanner>
        <ignoreUrl>.*logout.*</ignoreUrl>
        <spiderUrl>baseUrl</spiderUrl>
    </scanner>

    
    <upstreamProxy>
        <host></host>
        <port></port>
    </upstreamProxy>

    <incorrectPassword>SDFsdfwjx1</incorrectPassword>
    <incorrectUsername>bobbles</incorrectUsername>

    
    <nessus>
        <username>continuum</username>
        <password>continuum</password>
    </nessus>

    

    <zapPath>zap/zap.bat</zapPath>

</web-app>

**Comment by JMVM** [comment]
Try using proper ZAP sources in project
