### ISSUE TITLE
Error shown in framework when we execute it with our web application: java.lang.NumberFormatException: For input string: "window"

### ISSUE THREAD

**Issue by poojagangurde** [continuumsecurity/bdd-security#74]
Error shown in framework when we execute it with our web application: java.lang.NumberFormatException: For input string: "window"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) 
at java.lang.Integer.parseInt(Integer.java:580) 
at java.lang.Integer.parseInt(Integer.java:615) 
at net.continuumsecurity.proxy.ZAProxyScanner.validZAPVersion(ZAProxyScanner.java:74) 
at net.continuumsecurity.proxy.ZAProxyScanner.validateMinimumRequiredZapVersion(ZAProxyScanner.java:88) 
at net.continuumsecurity.proxy.ZAProxyScanner.(ZAProxyScanner.java:38) 
at net.continuumsecurity.steps.AppScanningSteps.getScanner(AppScanningSteps.java:81) 
at net.continuumsecurity.steps.AppScanningSteps.disableAllScanners(AppScanningSteps.java:76) 
at ✽.And a scanner with all policies disabled(passive_scan.feature:8) 

We have set the config.xml file correctly and edited all the fields in RopeyTasksApplication.java to test an example in our application. Chrome browser opens correctly and loads our application. But, each scenario gives an error of 'NumberFormatException' and all steps fail. Is there something that we are missing? Can we check some working example. Also, when tried to debug this in eclipse, there is an error of ZAProxyScanner and AppScanningSteps stating that The type org.zaproxy.clientapi.core.Alert cannot be resolved. It is indirectly referenced from required .class files.

**Comment by stephendv1** [comment]
Are you using the embedded version of ZAP, or a version that you downloaded?
To use the embedded ZAP the config.xml section should be:
`


    <zapPath>zap/zap.sh</zapPath>
`
I.e. the proxy section should be commented out and only the zapPath element should be present.
